#pragma once

#include "Logging/LogMacros.h"


#if UE_BUILD_SHIPPING
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGF, Warning, Display);
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGFGameDefinition, Warning, Display);
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGFAbilities, Warning, Display);
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGFInput, Warning, Display);
#elif UE_BUILD_TEST
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGF, Display, Log);
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGFGameDefinition, Display, Log);
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGFAbilities, Display, Log);
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGFInput, Display, Log);
#else // UE_BUILD_DEVELOPMENT ou UE_BUILD_DEBUG
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGF, Log, All);
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGFGameDefinition, Log, All);
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGFAbilities, Log, All);
	TP_MGF_API DECLARE_LOG_CATEGORY_EXTERN(LogTP_MGFInput, Log, All);
#endif